### PR TITLE
Update nickname-changes.yml

### PR DESCRIPTION
**Pull request by Bernatix**

### CODE REVIEW

**Comment by ScalaWilliam** [comment]
I can't see user `1414`: https://actionfps.com/player/?id=1414

**Comment by Bernatix** [comment]
sry! i was a little confused. My id is bernatix

https://imgur.com/a/PQ393

**Comment by ScalaWilliam** [comment]
Your effective date would cancel away many games you played. Are you sure you want August 2016 and not 10/Nov/2016?

**Comment by Bernatix** [comment]
Okay for me no problem!

**Comment by ScalaWilliam** [comment]
Done :-)

**Comment by Bernatix** [comment]
Thank you!

**Comment by ScalaWilliam** [comment]
This is done

**Pull request closed without merging**
